### ISSUE TITLE
The COVID dataset is missing

### ISSUE THREAD

**Issue by Perevalov** [tamlhp/kbqa#1]
The readme of this repo says:

```
In this work, we are also releasing a dataset for COVID-19. The dataset is provided in folder [COVID_data](https://github.com/tamlhp/kbqa/tree/main/data/COVID) in this repository. More details about dataset are provided below.
```

However, the COVID_data is missing. Could you upload this?

**Comment by Perevalov** [comment]
Any updates?

**Comment by kvt0012** [comment]
Dear you, 
I'm sorry for missing your issue.
However, because this dataset related to our thesis's member, so it's a little bit late when released. We will update it soon, but if you want to get it, you must sign some regulations.
Thanks for your concerning.

**Comment by kvt0012** [comment]
Dear you, If you are interested in our dataset, please contact via my email: khiemtv@uit.edu.vn
Thanks
